# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8scli < Formula
  desc "Kubernetes CLI helper tool"
  homepage "https://github.com/1985epma/k8scli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.0/k8scli_0.1.0_darwin_amd64.tar.gz"
      sha256 "ef4675b1d5a887acd0e39e5ce30b5ab188de9efd10b34b78642ff7fdc0fb28b9"

      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.0/k8scli_0.1.0_darwin_arm64.tar.gz"
      sha256 "3a07ec12faa7a7f93272651ecb83943317f2640078fc30aff93a4daf475cdf9f"

      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.0/k8scli_0.1.0_linux_amd64.tar.gz"
      sha256 "e3d92642da132349f61d94e69bfe97f0036e40995c777249334ab1f4a298aa12"
      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.0/k8scli_0.1.0_linux_arm64.tar.gz"
      sha256 "c7917ff006fcd01c54123bdd2f787aa25706d84148a531280459d576da2adfb0"
      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
  end

  test do
    system "#{bin}/k8scli", "help"
  end
end
