# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8scli < Formula
  desc "Kubernetes CLI helper tool"
  homepage "https://github.com/1985epma/k8scli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.1/k8scli_0.1.1_darwin_amd64.tar.gz"
      sha256 "874bc58d74a26d75fbfc24e246d2d10bc8bd8c7c152c1190c5802413200a87b7"

      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.1/k8scli_0.1.1_darwin_arm64.tar.gz"
      sha256 "2389539ace534c295ee0d4652aa07bc11fefeac4354ac781f068ad676d5c3184"

      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.1/k8scli_0.1.1_linux_amd64.tar.gz"
      sha256 "3091e49dd26f73152cd042152b5b4ecabf624578d15e1ced686c891f808f108f"
      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1985epma/k8scli/releases/download/v0.1.1/k8scli_0.1.1_linux_arm64.tar.gz"
      sha256 "b74c0eb091b8e5e1933d0dcb45592c8b3533b11f162566fca0464ea7b591e825"
      define_method(:install) do
        bin.install "k8scli"
        generate_completions_from_executable(bin/"k8scli", "completion")
      end
    end
  end

  test do
    system "#{bin}/k8scli", "help"
  end
end
